name: cicd
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: echo "Hello World"

  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
