name: cicd
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run: echo "Hello World"

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
        
      - name: Install Dependencies 
        run: |
          pip install -r requirements.txt

      - name: Test
        run: pytest -v 
