name: Test and Build
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - run: |
          cd app  
          pip install -r requirements.txt
          pytest -v 
